[project]
name = "grpo-modal"
version = "0.1.0"
description = "GRPO training with Modal"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
dependencies = [
    "datasets>=4.0.0",
    "huggingface-hub>=0.34.3",
]
